DROP DATABASE mangos;
CREATE DATABASE mangos DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON *.* TO 'mangos'@'%' IDENTIFIED BY 'mangos';
FLUSH PRIVILEGES;
GRANT ALL ON mangos.* TO mangos@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
